version: '3.5'

services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "6000:6000"
    env_file:
      - docker.env

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:  
  mongodb:
  mongodb_config: